---
- name: Hetzner server for FLWSB backend
  hosts: FLWSB_hetzner
  user: '{{ user }}'
  vars:
    is_hetzner: false # Change this to flase when you want to run it on a VM locally
    domains:
      - zanzi-test-2-grafana.aplab.be
      - zanzi-test-2-api.aplab.be
  roles:
    - ufwinstall
  tasks:

# RUN THIS PLAYBOOK: ansible-playbook -K -i ansible.cfg FLWSB-backend-ansible.yaml
# -K -> ask become password (root)
# -i -> specify ansible config file
# optional: add -v, -vv or -vvv to increase verbosity (more logs, handy when troubleshooting)

    - name: Update system
      ansible.builtin.include_role:
        name: updateall

    - name: Free services running on port 80 by default
      ansible.builtin.include_role:
        name: clear_port80-services

    - name: install dependencies
      ansible.builtin.include_role:
        name: install_dependencies_FLWSB

    - name: Install docker - debian
      ansible.builtin.include_role:
        name: install-docker-debian
      when: ansible_os_family == 'Debian'

    - name: Install docker - rocky
      ansible.builtin.include_role:
        name: install-docker-rocky
      when: ansible_os_family == 'Rocky'

    - name: Copy files to remote server
      ansible.builtin.include_role:
        name: copy_files

    - name: Copy nginx.conf if running locally
      ansible.builtin.copy:
        src: ~/zanzi-infra/ansible/roles/nginx.conf
        dest: ~/zanzi-infra/src/nginx/nginx.conf
        mode: preserve
      when: not is_hetzner

    - name: Generate SSL certificates
      ansible.builtin.command: certbot certonly --agree-tos --email "{{ email }}" --standalone -d {{ item }}
      args:
        creates: "/etc/letsencrypt/live/{{ item }}"
      with_items: "{{ domains }}"
      become: true
      when: is_hetzner

    - name: Renew certificates
      ansible.builtin.cron:
        name: "Renew SSL certs"
        job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"
        minute: "0"
        hour: "0"
        weekday: "1"
        # crontab runs every monday at 00:00
      when: is_hetzner

    - name: Bring docker compose up
      community.docker.docker_compose:
        project_src: ~/zanzi-infra/src/
        files:
          - docker-compose.yaml
      become: true
