---
- name: Generate SSL certificates
  ansible.builtin.command: certbot certonly --agree-tos --email "{{ email }}" --standalone -d {{ item }}
  args:
    creates: "/etc/letsencrypt/live/{{ item }}"
  with_items: "{{ domains }}"
  become: true

- name: Renew certificates
  ansible.builtin.cron:
    name: "Renew SSL certs"
    job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"
    minute: "0"
    hour: "0"
    weekday: "1"
    # crontab runs every monday at 00:00