- name: update for other Red Hat-based systems
  dnf:
    name: '*'
    state: latest

- name: Update the package cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install dnf-automatic
  ansible.builtin.dnf:
    name:
      - dnf-automatic
    state: present

- name: Enable a timer unit for dnf-automatic
  ansible.builtin.systemd_service:
    name: dnf-automatic.timer
    state: started
    enabled: true