---
- name: Add docker repository
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker packages
  ansible.builtin.command: dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin

- name: Add user to docker group
  user:
    name: "{{ user }}"
    append: yes
    groups: docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Verify install
  community.docker.docker_container:
    name: HelloWorld
    image: hello-world